# Generated by Django 2.1.5 on 2019-04-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
