# Generated by Django 2.1.5 on 2019-04-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_bot_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
    ]
