# Generated by Django 2.1.5 on 2019-04-13 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_bot_games_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='last_played',
            field=models.DateTimeField(default=datetime.datetime(2009, 12, 20, 0, 0)),
        ),
    ]
