# Generated by Django 2.1.5 on 2019-04-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_bot_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='l',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bot',
            name='w',
            field=models.IntegerField(default=0),
        ),
    ]
