# Generated by Django 2.1.5 on 2019-04-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0006_auto_20190414_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='d',
            field=models.IntegerField(default=0),
        ),
    ]
