# Generated by Django 2.1.5 on 2019-04-14 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0007_bot_d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='file',
        ),
    ]
