# Generated by Django 2.2 on 2019-04-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20190413_0815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='file',
            new_name='game_file',
        ),
        migrations.AddField(
            model_name='game',
            name='renderer_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
