# Generated by Django 2.2 on 2019-04-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20190414_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_file',
            field=models.FileField(null=True, upload_to='games/files/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='renderer_file',
            field=models.FileField(null=True, upload_to='games/files/'),
        ),
    ]
