# Generated by Django 2.1.5 on 2019-04-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20190414_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchrecord',
            name='did_bot1_win',
        ),
        migrations.AddField(
            model_name='matchrecord',
            name='winner_number',
            field=models.IntegerField(default=0),
        ),
    ]
