# Generated by Django 2.2 on 2019-04-14 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20190414_0226'),
        ('games', '0005_auto_20190414_0122'),
    ]

    operations = [
    ]
