<<<<<<< HEAD
# Generated by Django 2.1.5 on 2019-04-14 02:50
=======
# Generated by Django 2.2 on 2019-04-14 02:50
>>>>>>> animation-page

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('games', '0005_auto_20190414_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchrecord',
            name='did_bot1_win',
        ),
        migrations.AddField(
            model_name='matchrecord',
            name='winner_number',
            field=models.IntegerField(default=0),
=======
        ('games', '0005_auto_20190414_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_file',
            field=models.FileField(null=True, upload_to='games/files/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='renderer_file',
            field=models.FileField(null=True, upload_to='games/files/'),
>>>>>>> animation-page
        ),
    ]
