# Generated by Django 2.1.5 on 2019-04-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20190414_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='renderer_file',
            field=models.TextField(default='bad display'),
            preserve_default=False,
        ),
    ]
