# Generated by Django 2.1.5 on 2019-04-14 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20190414_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_file',
        ),
    ]
